"""esquema inicial

Revision ID: 7e887f9ea48e
Revises: 
Create Date: 2026-10-08 16:56:54.721753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e887f9ea48e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Segmentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('criterios', sa.JSON(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tipos_interaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('requiere_seguimiento', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('contrasena', sa.String(length=128), nullable=False),
    sa.Column('creacion', sa.DateTime(), nullable=True),
    sa.Column('actualizado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('Catalogo_recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=True),
    sa.Column('tipo_recomendacion', sa.String(length=500), nullable=False),
    sa.Column('reglas', sa.JSON(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['segmento_id'], ['Segmentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segmento_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('ultima_compra', sa.DateTime(), nullable=True),
    sa.Column('total_compras', sa.Float(), nullable=True),
    sa.Column('frecuencia_compra', sa.Float(), nullable=True),
    sa.Column('valor_medio_orden', sa.Float(), nullable=True),
    sa.Column('probabilidad_churn', sa.Float(), nullable=True),
    sa.Column('valor_cliente', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('telefono', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['segmento_id'], ['Segmentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Interacciones_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_interaccion_id', sa.Integer(), nullable=False),
    sa.Column('data_interaccion', sa.JSON(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.ForeignKeyConstraint(['tipo_interaccion_id'], ['Tipos_interaccion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Metricas_historicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_metrica', sa.String(length=500), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('periodo', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_prediccion', sa.String(length=500), nullable=False),
    sa.Column('valor_prediccion', sa.JSON(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('catalogo_recomendacion_id', sa.Integer(), nullable=True),
    sa.Column('data_recomendacion', sa.JSON(), nullable=False),
    sa.Column('aplicada', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_recomendacion_id'], ['Catalogo_recomendaciones.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['Clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interacciones_cliente', schema=None) as batch_op:
        batch_op.drop_index('idx_cliente_id_interacciones_cliente')
        batch_op.drop_index('idx_tipo_interaccion_id_interacciones_cliente')
        batch_op.drop_index('idx_usuario_id_interacciones_cliente')

    op.drop_table('interacciones_cliente')
    with op.batch_alter_table('recomendaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_catalogo_recomendacion_id_recomendaciones')
        batch_op.drop_index('idx_cliente_id_recomendaciones')

    op.drop_table('recomendaciones')
    with op.batch_alter_table('catalogo_recomendaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_segmento_id_catalogo_recomendaciones')

    op.drop_table('catalogo_recomendaciones')
    op.drop_table('usuario')
    with op.batch_alter_table('metricas_historicas', schema=None) as batch_op:
        batch_op.drop_index('idx_cliente_id_metricas_historicas')

    op.drop_table('metricas_historicas')
    op.drop_table('tipos_interaccion')
    op.drop_table('predicciones')
    op.drop_table('segmentos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index('idx_segmento_id_clientes')

    op.drop_table('clientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('segmento_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('ultima_compra', mysql.DATETIME(), nullable=True),
    sa.Column('total_compras', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('frecuencia_compra', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('valor_medio_orden', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('probabilidad_churn', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('valor_cliente', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=False),
    sa.Column('churn', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('telefono', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('churn_value', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], name='FK_Cliente_Segmento', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index('idx_segmento_id_clientes', ['segmento_id'], unique=False)

    op.create_table('segmentos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('criterios', mysql.JSON(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('predicciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_prediccion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('valor_prediccion', mysql.JSON(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='FK_Predicciones_Cliente', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tipos_interaccion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('requiere_seguimiento', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('metricas_historicas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_metrica', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('valor', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=False),
    sa.Column('periodo', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='FK_Metricas_Cliente', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('metricas_historicas', schema=None) as batch_op:
        batch_op.create_index('idx_cliente_id_metricas_historicas', ['cliente_id'], unique=False)

    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('contrasena', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('creacion', mysql.DATETIME(), nullable=False),
    sa.Column('actualizado', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('catalogo_recomendaciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('segmento_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_recomendacion', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('reglas', mysql.JSON(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], name='FK_Catalogo_Segmento', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('catalogo_recomendaciones', schema=None) as batch_op:
        batch_op.create_index('idx_segmento_id_catalogo_recomendaciones', ['segmento_id'], unique=False)

    op.create_table('recomendaciones',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('catalogo_recomendacion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_recomendacion', mysql.JSON(), nullable=False),
    sa.Column('aplicada', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_recomendacion_id'], ['catalogo_recomendaciones.id'], name='FK_Recomendaciones_Catalogo', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='FK_Recomendaciones_Cliente', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('recomendaciones', schema=None) as batch_op:
        batch_op.create_index('idx_cliente_id_recomendaciones', ['cliente_id'], unique=False)
        batch_op.create_index('idx_catalogo_recomendacion_id_recomendaciones', ['catalogo_recomendacion_id'], unique=False)

    op.create_table('interacciones_cliente',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_interaccion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_interaccion', mysql.JSON(), nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='FK_Interacciones_Cliente', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_interaccion_id'], ['tipos_interaccion.id'], name='FK_Interacciones_Tipo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='FK_Interacciones_Usuario', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('interacciones_cliente', schema=None) as batch_op:
        batch_op.create_index('idx_usuario_id_interacciones_cliente', ['usuario_id'], unique=False)
        batch_op.create_index('idx_tipo_interaccion_id_interacciones_cliente', ['tipo_interaccion_id'], unique=False)
        batch_op.create_index('idx_cliente_id_interacciones_cliente', ['cliente_id'], unique=False)

    op.drop_table('Recomendaciones')
    op.drop_table('Predicciones')
    op.drop_table('Metricas_historicas')
    op.drop_table('Interacciones_cliente')
    op.drop_table('Clientes')
    op.drop_table('Catalogo_recomendaciones')
    op.drop_table('Usuario')
    op.drop_table('Tipos_interaccion')
    op.drop_table('Segmentos')
    # ### end Alembic commands ###
